### PR TITLE
update react version

### PR DESCRIPTION
**Pull request by Wjpayne**
Need to update the react version, super simple

### CODE REVIEW

**Comment by pavelkukov** [comment]
Thank you, @Wjpayne!
Unfortunately, the build pipeline has failed. Maybe something is outdated... The new release is not published.

**Comment by Wjpayne** [comment]
weird! @pavelkukov this is the error I get

npm ERR! While resolving: synth-app@0.1.0                                       npm ERR! Found: react@18.2.0                                                    npm ERR! node_modules/react                                                     npm ERR!   react@"^18.2.0" from the root project                                npm ERR!                                                                        npm ERR! Could not resolve dependency:                                          npm ERR! peer react@"^17.0.1" from react-dial-knob@1.3.0                        npm ERR! node_modules/react-dial-knob                                           npm ERR!   react-dial-knob@"*" from the root project

**Comment by Wjpayne** [comment]
maybe update all npm packages. This is too perfect for my project right now ha

**Comment by Wjpayne** [comment]
actually I see the error now @pavelkukov 
image

[build (12.x)](https://github.com/pavelkukov/react-dial-knob/actions/runs/3049247500/jobs/4922734851#step:6:4)
The ssh-private-key argument is empty. Maybe the secret has not been configured, or you are using a wrong secret name in your workflow file.

**Comment by pavelkukov** [comment]
Yeah, the pipeline is old. The secret is there but for some reason, it is not working. I don't have time to fix this in the upcoming two weeks. You can fork and publish a new module to unblock your work.
Thank you for raising a PR and investigating the build issue! Please let me know if you publish it as a new module. I will put a link here to your alternative.

**Pull request merged**
